### ISSUE TITLE
Problems building the cFS

### ISSUE THREAD

**Issue by edison369** [alanc98/rtems-cfs-demo#1]
Hi @alanc98 !!,
My name is Edison, I didn't know how to contact you, that is why I made this issue. I am trying to build the cFS and RTEMS Kernel Image on a Raspberry Pi 3. I am using RTEMS 5 and as a host a virtual machine with Ubuntu 22.04.1 LTS.
I was able to build some RTEMS sample tests and also the RTEMS Kernel Image without the cFS. When I try to build the cFS I have some issues and I would like to ask you for some help or guidance. 
I am able to do:
`make SIMULATION=arm-raspberrypi2-rtems5 prep`
without problem. When I try to run the `make` command I have 4 issues in particular:

1. In the file </home/edimar369/Desktop/Demo_Edison/cFS/osal/src/os/rtems/src/os-impl-network.c> I get an implicit declaration of gethostname() so I added the prototype for the function in **os-impl-network.c** and it seemed to work.
2. In the file </home/edimar369/Desktop/Demo_Edison/cFS/osal/src/os/portable/os-impl-bsd-sockets.c> I get an error that says: "MSG_DONTWAIT' undeclared (first use in this function); did you mean 'MSG_DONTROUTE'" it is weird since both MSG_DONTWAIT and MSG_DONTROUTE are defined in socket.h. To solve this I added the MSG_DONTWAIT definition in the **os-impl-bsd-sockets.c** file.
3. In the files: 
</home/edimar369/Desktop/Demo_Edison/cFS/apps/to_lab/fsw/tables/to_lab_sub.c>
</home/edimar369/Desktop/Demo_Edison/cFS/apps/sch_lab/fsw/tables/sch_lab_table.c>
I get an error that says "fatal error: blinky_msgids.h: No such file or directory"
I opened blinky_msgids.h and found out that it has some definitions so I added this definitions into both  **to_lab_sub.c** and **sch_lab_table.c** to solve this error.
4. After solving the previous errors I run make again and I get lots of undefined reference errors as you can see in the picture attached

![Screenshot from 2022-10-06 12-34-16](https://user-images.githubusercontent.com/58643543/194381097-92ae1636-5a9a-4c8f-a767-25251de83e92.png)

I think all this errors are related but I don't know how to solve them. I hope you can help me with this! Thanks in advance

Edison

**Comment by alanc98** [comment]
Hi Edison,
Are you starting with this repository as your baseline? It's not the latest cFS or RTEMS, but a snapshot from the beginning of the year. My goal with the Docker containers was to try to make this demo reproducible exactly the way it was in January, and I was only focused on the BeagleBone Black with RTEMS 6.

I have seen problems 1 and 2, and they are related to the functions and headers that are available in a RTEMS build. I will have to dig up the source, but it's related to a specific define that enables the definitions. You said you are building for RTEMS 5, so that might be where those errors are coming from. Is there a reason you are using 5, and not the latest/6 branch of RTEMS?
If I have the time, I can dig out these repositories again and see if I can make it run on the Raspberry Pi 2 RTEMS BSP.

For problem 3, the apps like SCH_LAB and TO_LAB that include other apps message IDs must have the include path to that app (in this case Blinky). The include path is defined in the App's CMakelists.txt. Note that you may have to do some work to get blinky working on the raspberry Pi. I cannot recall what the state of the RPI RTEMS GPIO interface is, but I think it was working.
For problem 4, I will have to take a closer look. Again, it might be RTEMS 5 vs. 6 in this specific set of repositories. The latest official cFS repositories should build for RTEMS 4.11, RTEMS 5.1 (including Gaisler RCC 1.3.x), and RTEMS 6.

So I know it's a pain right now - This repo was built for RTEMS 6, and has the generic RTEMS Platform Support Package (PSP) that I used in the demo. The official repos build for all versions of RTEMS, but only have the "pc-rtems" PSP, so something must be ported over to get the specific combination you are looking for.

And for the RaspberryPi2 RTEMS BSP, that does not have network support, so CI_LAB and TO_LAB will not work. Is that OK with what you are trying to do?

Regards,
Alan

**Comment by edison369** [comment]
Hi Alan!

Thank you very much for your quick response!! To answer your question, I am using this repository as my baseline because I am new to the cFS and by reading [this cFS discussion](https://github.com/nasa/cFS/discussions/314) I realized I didn't know how to change the OSAL BSP or the PSP to make it work. Luckily I found this repository as well as the rki2 one.

I am using RTEMS 5 because I had some trouble installing RTEMS 6 at first, but now I installed it and will try to work with it instead and I will tell you what happens. I will try to use the latest cFS repositories and RTEMS 6 this time. About the "pc-rtems" PSP, as I told you I'm new to the cFS and I'm confused, I would appreciate if you could help me with the differences and changes that I should make in this new configuration.

I didn't know the RaspberryPi2 RTEMS BSP does not have network support. Then there is no way of making the telemetry system work right? Because I wanted to use the Raspberry Pi as the "nanosatellite" and my PC as ground control. The thing is that, what I am doing or trying to do is for my undergraduate thesis. Again, thank you very much for your help!

Regards,
Edison

**Comment by alanc98** [comment]
If network support is needed for your nanosatellite, you have options, but some are easier than others:

1. Use Linux on the Raspberry Pi - This is the easiest as you can have all kinds of network device support and the cFS runs without any modifications on linux
2. Use a board like the Beaglebone Black with RTEMS - just clone this repository
3. Add network support to the the RTEMS RaspberryPi BSP - This is a difficult option, but would be a welcome addition to the RTEMS raspberry Pi BSP
4. If you need to use a RTOS, there may be another RTOS that supports the Raspberry Pi 2 ethernet, but it would require a significant effort to port the cFS to a new RTOS

I have an example of how you can use Linux with my "nanosatellite" called proto-sat:
https://github.com/alanc98/ProtoSat

**Comment by edison369** [comment]
Thank you for the help!! I can't do option 1 since I have to use an RTOS. For now I will go for option 2 and if I have some time I'll try to do option 3, it looks as a fun challenge. Again, thank you very much for your help. Have a nice day!!

**Comment by alanc98** [comment]
No problem! Good luck on your project.
