### ISSUE TITLE
Pointer pointing to wrong address when using string literal directly

### ISSUE THREAD

**Issue by datnguyen31** [alanc98/rtems-cfs-demo#4]
Hello @alanc98 ,

I've been using your repository for a personal project to delve deeper into RTEMS. I followed your guide, and everything works perfectly with all the applications provided. However, I ran into a puzzling issue when I tried to import my own library. I’m having trouble figuring out what’s going wrong. You can find the repository for my library here:  [sample_lib](https://github.com/datnguyen31/sample_lib).

In short, here are some phenomena:
1. Pointer points to the wrong address when I pass a string literal directly into a function. For example: [here](https://github.com/datnguyen31/sample_lib/blob/main/fsw.3/mutex/dev_mutex.c). The string literal doesn't get passed correctly during the system call, and instead, a string from an unrelated location appears. I’ve tried two workaround solutions by creating variables to hold these literals, which seem to fix the issue temporarily, but I suspect the underlying problem is still present. You can take a look at [version 2](https://github.com/datnguyen31/sample_lib/blob/main/fsw.2/mutex/dev_mutex.c) and [version 1](https://github.com/datnguyen31/sample_lib/blob/main/fsw.1/mutex/dev_mutex.c).

Directly passing string literal example:
```
CFE_PSP_MemCpy(deviceID, "AAA", 1 + strlen("AAA"))
```

String from unrelated location:
```
strncpy(SAMPLE_Buffer, "SaMpLe", sizeof(SAMPLE_Buffer))
#define SAMPLE_LIB_VERSION_STRING "Sample Lib DEVELOPMENT BUILD "
OS_printf("SAMPLE Lib Initialized.%s\n", SAMPLE_LIB_VERSION_STRING);
```

Console result:
```
OS_MutSemCreate(0 - SaM): 0    /* The corrected string should be AAA */
OS_MutSemCreate(1 - Sam): 0    /* The corrected string should be AAB */
OS_MutSemCreate(2 - SAM): 0    /* The corrected string should be AAC */
OS_MutSemCreate(3 - AAD): 0    /* From this point that it got corrected string */
```

2. Related to the first issue, I didn’t see the problem with ci_lab, to_lab, and sch_lab. To test further, I added a file to_personal_custom.c with a function void foo(). In this file, I used a test string literal directly with CFE_PSP_MemCpy, similar to before, and called it before TO_LAB_init. The issue reappeared, with the test string unexpectedly appearing in CFE_SB_CreatePipe during the execution of TO_LAB_init.

3. Due to the issues mentioned above, I decided to examine the disassembly of the runtime-loaded modules. I observed numerous `<UNDEFINED>` and `<UNPREDICTABLE>` instructions in my repository, as well as in other applications like `to_lab` and `ci_lab`. I found an explanation [here](https://stackoverflow.com/questions/29505049/when-will-gcc-generate-undefined-instructions-for-function) suggesting that these might not be actual instructions but could be inline data.
So, could passing a string literal directly to a function be causing these <UNDEFINED> instructions (or inline data) and thereby leading to the issues described above?

I would greatly appreciate it if you could take some time to look into these problems. Thank you!

Best regards,
Dat Nguyen

**Comment by alanc98** [comment]
Hi @datnguyen31 , 
This may be a problem with the RTEMS dynamic loader. At the time of the demo, there were some problems with the dynamic loader for the ARM architecture. There may be problems with other architecture implementations for the loader such as RISC-V.

SPARC is known to work well for complex cFS applications and libraries.

Potential solutions include:
1. Link the cFE core and apps as one object. I know that the latest cFS CMakefiles support doing this, I'm not sure if the commit used for this demo has the same support, but it's worth checking. The settings would be in the targets.cmake file for the cFS.
2. See if the newer RTEMS 6 commit has updates to the dynamic loader - I'm not sure if the RTEMS release could simply be bumped up, or if there are changes needed to this repo to account for any changes. This repo is due for an update anyway due to the RTEMS repos transitioning to gitlab.

You could take a look at the dynamic loader files in the latest RTEMS repo vs. the commit used for this demo.

But the quick solution would be to just use the static link option to link your apps and libs to the cFE core in the sample_defs/targets.cmake file (hopefully that is supported in the commit I used for this demo)

I hope this helps,
Alan

**Comment by datnguyen31** [comment]
Hi @alanc98 ,

Thank you for your information about the ARM architecture. I will review the source code and explore the options you’ve mentioned.

I'll close the issue for now and reopen it if any further questions arise.

Thanks again for your help!

Best regards,
Dat Nguyen
